server:
  port: 8013
spring:
  application:
    name: quote-service
  datasource:
    url: jdbc:mysql://localhost:3306/smartcrm_quotes?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root123
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-type: mysql